### ISSUE TITLE
bug in update_id_changes

### ISSUE THREAD

**Issue by ThomasKraft** [babeheim/longformer#3]
Format of the "id_changes" table was recently changed in transition to "pid_changes."

Simple fix I implemented locally that works is to:
1) remove this line: https://github.com/babeheim/longformer/blob/b991a0aafc668346b230f1c1223aa9677ef66016/R/appending_functions.R#L4

2) remove "type" from this line: https://github.com/babeheim/longformer/blob/b991a0aafc668346b230f1c1223aa9677ef66016/R/appending_functions.R#L15

**Comment by babeheim** [comment]
fixed, thanks Tom!

**Comment by ThomasKraft** [comment]
This issue still arises because the `update_id_changes` is defined twice in your scripts (look in updating_functions and appending_functions). That explains why it didn't appear to be updating when I reinstalled...

**Comment by babeheim** [comment]
Fixed
